name: Run tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        

      - name: install dependencies
        run: npm ci
    
      - name: build image
        run: docker compose -f docker-compose.test.yml build

      - name: bring up environment
        run: docker compose -f docker-compose.test.yml up -d

      - name: run tests
        run: docker compose -f docker-compose.test.yml run pokemon_web_tests run testAll --prefix /test
